### PR TITLE
Update mkkmeans_train.R

### PR DESCRIPTION
**Pull request by GengxinXu**
add a line of code to library the package Matrix, which contains the function Matrix

### CODE REVIEW

**Comment by mehmetgonen** [comment]
library(Rmosek) line adds Matrix library.

**Comment by GengxinXu** [comment]
> library(Rmosek) line adds Matrix library.

After library(Rmosek), I should manually library(Matrix). Why?

**Comment by mehmetgonen** [comment]
When you execute library(Rmosek) line, it should load Matrix package automatically since Rmosek package depends on Matrix package.

Here is an example output:
>library(Rmosek)
Loading required package: Matrix

**Comment by GengxinXu** [comment]
> When you execute library(Rmosek) line, it should load Matrix package automatically since Rmosek package depends on Matrix package.
> 
> Here is an example output:
> 
> > library(Rmosek)
> > Loading required package: Matrix

Thanks for your reply. Maybe the MOSEK has not been installed correctly on my computer. Now I install it again.

**Pull request closed without merging**
